name: AGP

on:
  schedule:
    - cron: "0 * * * *" #hourly

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: AGP
        uses: ms-jpq/auto-github-push/v1
        token: ${{ secrets.CI_TOKEN }}
        uses: hisasann/simple-github-auto-push@main
        env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        BRANCH_NAME: main
